### PR TITLE
Update create.js

### PR DESCRIPTION
**Pull request by Hypercubed**
Require is not loading `package.json` from the CWD during create.

### CODE REVIEW

**Comment by Hypercubed** [comment]
I believe you have to do the same here... https://github.com/Wizcorp/climaker/blob/master/commands/climaker/command/create.js#L3 require is not relative to the CWD.

**Comment by stelcheck** [comment]
Could you update command/create as well? I believe you are right, this should be going through `path`.

**Comment by Hypercubed** [comment]
Done.

**Comment by stelcheck** [comment]
I'll merge this PR into the develop branch, and release it a bit later. Thanks for your help!

**Comment by stelcheck** [comment]
Just merged to develop, closing.

**Pull request closed without merging**
